# \uC8FC\uC758: \uD55C\uAE00 \uC8FC\uC11D\uC744 \uB2EC\uB824\uBA74 UTF-8\uC744 \uC774\uC6A9\uD574\uC57C \uD569\uB2C8\uB2E4!! \uAE30\uBCF8\uAC12\uC774 ISO-8859-1\uC778\uB370, \uD574\uB2F9 \uC778\uCF54\uB529\uC740 \uD55C\uAE00\uC774 \uAE68\uC9D1\uB2C8\uB2E4.

# \uB85C\uCEEC properties\uAC00 \uC874\uC7AC\uD560 \uACBD\uC6B0, \uD574\uB2F9 properties\uB97C \uAC00\uC838\uC640\uC11C \uB36E\uC5B4 \uC50C\uC6C1\uB2C8\uB2E4.
spring.config.import=optional:classpath:application-local.properties

spring.application.name=whatshu_be

# \uD68C\uC6D0 \uAD6C\uD604 \uC644\uB8CC\uB418\uAE30 \uC804\uAE4C\uC9C0\uB294 \uC774\uAC78\uB85C \uB85C\uADF8\uC778\uD558\uC2DC\uBA74 \uB429\uB2C8\uB2E4.
spring.security.user.name=user
spring.security.user.password=password

# H2 \uCF58\uC194\uC744 \uD65C\uC131\uD654
spring.h2.console.enabled=true

# MyBatis \uC124\uC815
mybatis.configuration.map-underscore-to-camel-case=true

# DB \uCD08\uAE30\uD654
spring.sql.init.schema-locations=classpath:sql/schema.sql

# === 2. H2 \uC124\uC815\uC740 \uC0AD\uC81C (MySQL \uC4F8 \uAC70\uB2C8\uAE4C) ===
# spring.h2.console.enabled=true  <-- \uC774\uAC74 \uD544\uC694 \uC5C6\uC5B4\uC11C \uC8FC\uC11D \uCC98\uB9AC\uD568

# === 3. MySQL(RDS) \uC124\uC815 \uCD94\uAC00 ===
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# [\uC911\uC694] \uC544\uB798 \uC8FC\uC18C\uC5D0\uC11C [\uC5D4\uB4DC\uD3EC\uC778\uD2B8]\uC640 [mysql] \uBD80\uBD84\uC744 \uD655\uC778\uD558\uC138\uC694!
spring.datasource.url=jdbc:mysql://gdg-whatsu.ch40gmaiabt6.ap-northeast-2.rds.amazonaws.com:3306/gdg_whatsu_rds?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

# [\uC911\uC694] \uBCF8\uC778\uC758 RDS \uC544\uC774\uB514\uC640 \uBE44\uBC00\uBC88\uD638\uB97C \uC801\uC73C\uC138\uC694
spring.datasource.username=${RDS_USERNAME}
spring.datasource.password=${RDS_PASSWORD}


# JPA \uC124\uC815 (\uD14C\uC774\uBE14 \uC790\uB3D9 \uAD00\uB9AC)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true


# JWT \uBE44\uBC00\uD0A4
jwt.secret=${JWT_SECRET_KEY}
# \uD1A0\uD070 \uC720\uD6A8\uC2DC\uAC04 (5\uBD84)
jwt.expiration=5

# QR 코드 토큰 관련
qr.token.secret=${QR_TOKEN_SECRET_KEY}
qr.token.exp.minutes=1
