# 주의: 한글 주석을 달려면 UTF-8을 이용해야 합니다!! 기본값이 ISO-8859-1인데, 해당 인코딩은 한글이 깨집니다.

# 로컬 properties가 존재할 경우, 해당 properties를 가져와서 덮어 씌웁니다.
spring.config.import=optional:classpath:application-local.properties

spring.application.name=whatshu_be

# 회원 구현 완료되기 전까지는 이걸로 로그인하시면 됩니다.
spring.security.user.name=user
spring.security.user.password=password

# H2 콘솔을 활성화
spring.h2.console.enabled=true

# MyBatis 설정
mybatis.configuration.map-underscore-to-camel-case=true

# DB 초기화
spring.sql.init.schema-locations=classpath:sql/schema.sql

# === 2. H2 설정은 삭제 (MySQL 쓸 거니까) ===
# spring.h2.console.enabled=true  <-- 이건 필요 없어서 주석 처리함

# === 3. MySQL(RDS) 설정 추가 ===
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# [중요] 아래 주소에서 [엔드포인트]와 [mysql] 부분을 확인하세요!
spring.datasource.url=jdbc:mysql://gdg-whatsu.ch40gmaiabt6.ap-northeast-2.rds.amazonaws.com:3306/gdg_whatsu_rds?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

# [중요] 본인의 RDS 아이디와 비밀번호를 적으세요
spring.datasource.username=${RDS_USERNAME}
spring.datasource.password=${RDS_PASSWORD}


# JPA 설정 (테이블 자동 관리)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true


# JWT 비밀키
jwt.secret=${JWT_SECRET_KEY}
# 토큰 유효시간 (5분)
jwt.expiration=5
